### ISSUE TITLE
Add UKPN analytics

### ISSUE THREAD

**Issue by slowe** [odileeds/ukpowernetworks#1]
Add the code for UKPN analytics. This will also need a privacy notice and, most-likely, a cookie notice.

**Comment by ash001j** [comment]
Have found the code for GA, unsure where to put it in the repository

**Comment by slowe** [comment]
@ash001j Hopefully it resembles some code wrapped in `<script>....</script>` tags. Assuming it does, you need to add it to the bottom of the index.html file before the `</body>`.

**Comment by slowe** [comment]
I think this is working now. You may need to write some text about cookies/privacy now that there is tracking enabled.

**Comment by slowe** [comment]
The cookie notice is now included at the bottom of the page.
