### ISSUE TITLE
Add view by County

### ISSUE THREAD

**Issue by slowe** [odileeds/ukpowernetworks#10]
We will need:
- [x] Mapping from LSOA to County
- [x] Get GeoJSON for County (non-overlapping and clipped to UKPN licence area)

**Comment by slowe** [comment]
ONS generalised clipped boundaries for Counties (Dec 2019) are at https://geoportal.statistics.gov.uk/datasets/counties-december-2019-boundaries-en-bgc

**Comment by slowe** [comment]
@ash001j The county boundaries (above) have gaps in.
![Screenshot_2020-10-20 geojson io](https://user-images.githubusercontent.com/299787/96613851-578ccf00-12f7-11eb-8c29-44109017c3ac.png)

**Comment by slowe** [comment]
County/unitary authority boundaries have been provided by @ash001j. We still need to make a file with the mapping from LSOA11CD to these area codes.

**Comment by slowe** [comment]
The names of the counties in the GeoJSON had been truncated so I've added these back by hand.

In the CSV that maps LSOA/MSOA/LAD/CTY the LSOA "E01021893" ("Maldon 005A") had "at" instead of the `ctyua19cd` code for Essex. I altered that by hand.

**Comment by gilesdring** [comment]
@slowe Could you let me know where we're up to on this?

**Comment by slowe** [comment]
@gilesdring From my perspective this issue is finished. It'd be great if @ash001j could review what's been done (including my hand-fixes mentioned above) and close it.
