### ISSUE TITLE
Exporting map as image

### ISSUE THREAD

**Issue by ash001j** [odileeds/ukpowernetworks#14]
Additional functionality to export the current map as an image. Need to discuss the format.

**Comment by slowe** [comment]
@ash001j @VT-UKPN Patrick and I had mentioned SVG but I think I remember you saying the image saving was mostly for people to be able to copy views into, say, Powerpoint. So we've gone with saving as PNG as that feels the most robust for that type of thing. There's now a link, below the map, saying "Save map as PNG". It saves the map, the year, and the copyright notice at the bottom. It doesn't include the zoom/search buttons.

**Comment by ash001j** [comment]
Need to add in the legend and associated metadata, as per email.

**Comment by slowe** [comment]
![map-6](https://user-images.githubusercontent.com/299787/98970279-a77e4080-2507-11eb-8229-90a7259bb72f.png)
Here's what a screenshot now looks like. Just a note that the scale bar's right-hand line shouldn't be over on the left; I don't know why it is appearing over there and am not sure how to fix it.

**Comment by ash001j** [comment]
Looks perfect, happy to close the issue now, thanks.
