### ISSUE TITLE
Adding Local Authority boundaries for LSOA view

### ISSUE THREAD

**Issue by ash001j** [odileeds/ukpowernetworks#15]
When viewing the LSOAs, it is hard to distinguish between different Local Authorities. Leaving in the LA boundaries when on LSOA view will make it more useful for people trying to see the situation within their LA.

**Comment by slowe** [comment]
I've trimmed some slivers of Local Authorities that were caused by mismatching of the UKPN boundaries with the LAD boundaries (mostly down to different resolution). This reduces the LAD GeoJSON file size.
